### PR TITLE
Added detection to preview mails with attachments

### PR DESCRIPTION
**Pull request by aelesbao**
Hi,

I did this patch to fix some issues that we were having to display emails with attachments. Hope you enjoy.

Thanks,
Augusto

### CODE REVIEW

**Comment by wireframe** [comment]
any chance you have a gist or testcase for the issue you were experiencing?  i'd be interested to smoke test it locally and see how it breaks.

ex:

``` ruby
EmailPreview.register 'multipart w/ attachments' do
  Mail.new do
    to 'tom@example.com'
    from 'me@foo.com'
    body 'check this out'
    # attach a file?
  end
end
```

**Comment by aelesbao** [comment]
Here it is: https://gist.github.com/2955549

**Comment by wireframe** [comment]
thanks again for the patch.  I've pulled down the patch and tested locally with the example rails app packaged in the gem.  There seems to be a slight issue where it is listing duplicate txt parts in the web ui.
https://img.skitch.com/20120702-8b1dm89trkhrxejg9tytwnbhk5.jpg

**Comment by wireframe** [comment]
closing out issue as it introduces regressions to existing functionality.

**Pull request closed without merging**
